<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connexion</name>
   <tag></tag>
   <elementGuidId>3778584d-0aad-44f0-a827-55b8ce8b49b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_desktop_user_info']/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.hidden-sm-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>609d5542-b107-4bdf-958d-979ddb85ff02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-sm-down</value>
      <webElementGuid>0bf70bde-225b-4a13-b078-c0db2e17de2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connexion</value>
      <webElementGuid>bcd857bf-e639-4cc2-8234-a1d83821f676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_desktop_user_info&quot;)/div[@class=&quot;user-info&quot;]/a[1]/span[@class=&quot;hidden-sm-down&quot;]</value>
      <webElementGuid>8e60149a-6678-496d-a8de-4b9be5310a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_desktop_user_info']/div/a/span</value>
      <webElementGuid>bec90a32-7cf9-435b-b531-af2c3c043a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>12006a86-8d7a-4aca-a241-a82b2a93416e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Connexion' or . = 'Connexion')]</value>
      <webElementGuid>bd7843e0-0262-4a64-83b2-f6e6137b1e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
