<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enregistrer</name>
   <tag></tag>
   <elementGuidId>8f0cd17d-61d7-4caf-8e04-1e391d2c1bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.form-control-submit.float-xs-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>727ba99b-3765-4895-b28f-57e5c0f8eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary form-control-submit float-xs-right</value>
      <webElementGuid>2e2a8030-f0df-4072-81bc-f85a086e003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link-action</name>
      <type>Main</type>
      <value>save-customer</value>
      <webElementGuid>1f8559c0-6a1b-4008-8366-c778a1beb65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1b17f6a4-9478-43b0-8c87-40464e469750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Enregistrer
        </value>
      <webElementGuid>a9e9b31a-f602-412c-887e-f027cb65ab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-form&quot;)/footer[@class=&quot;form-footer clearfix&quot;]/button[@class=&quot;btn btn-primary form-control-submit float-xs-right&quot;]</value>
      <webElementGuid>34adb82e-7ceb-4661-85cb-4111b4d785e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>6cb49086-fcc7-4732-8463-e36d262f9ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/footer/button</value>
      <webElementGuid>fa9cb6df-cc35-400e-93e2-6e24b93ac11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button</value>
      <webElementGuid>4064930b-2ac8-4eb6-970a-ebd405c95500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
          Enregistrer
        ' or . = '
          Enregistrer
        ')]</value>
      <webElementGuid>ee7c0dc6-5831-44ae-9976-d8ce25da8d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
