<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_newsletter</name>
   <tag></tag>
   <elementGuidId>5882ffc3-3305-4661-8344-decff95ae282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='newsletter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;newsletter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8765fa2-0387-4e22-80a8-9ef9b887aabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>156733f6-396b-4ad4-b3d2-e0f5f671422c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dd9a443c-fb9d-4310-8f01-e16f5621834f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>578e346f-cf7a-4eae-83d4-8018c8a7a946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-form&quot;)/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6&quot;]/span[@class=&quot;custom-checkbox&quot;]/label[1]/input[1]</value>
      <webElementGuid>6f0465ef-aa1f-48f5-b2a1-38cef7236fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='newsletter']</value>
      <webElementGuid>e131952c-2d64-467b-8c8e-9c6592eeb51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/div/div[9]/div/span/label/input</value>
      <webElementGuid>9fd7b0f9-c6d0-45d1-a952-868343fe20cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span/label/input</value>
      <webElementGuid>deb67a31-9928-44ec-a0b9-1bbcdb361737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'newsletter' and @type = 'checkbox']</value>
      <webElementGuid>b29b3c8e-a089-49c2-b821-3df8d1da5499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
