<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_psgdpr</name>
   <tag></tag>
   <elementGuidId>da482641-49c4-4195-91f0-52dbba942baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='psgdpr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;psgdpr&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68a73536-3693-464b-b400-9805173b6421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>psgdpr</value>
      <webElementGuid>a54ea814-87f0-46c6-bcfe-3b2ad634cb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e28e6a98-189a-4248-9916-bffdffa1b1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>15853952-ec18-4cdf-8337-38fe5cfb0f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-form&quot;)/div[1]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-md-6&quot;]/span[@class=&quot;custom-checkbox&quot;]/label[1]/input[1]</value>
      <webElementGuid>8a725b0d-6f25-4353-ad85-579f5a6105dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='psgdpr']</value>
      <webElementGuid>09f7f3f9-8d52-460e-a466-7877b40d1a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/div/div[10]/div/span/label/input</value>
      <webElementGuid>1cbf4852-3be9-4f95-999a-5fe134b0b564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/span/label/input</value>
      <webElementGuid>082d3bfc-3700-4bdd-bdda-864db829b553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'psgdpr' and @type = 'checkbox']</value>
      <webElementGuid>6b206b22-a15f-4192-886b-0234446b53cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
