<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_id_gender</name>
   <tag></tag>
   <elementGuidId>17567545-c4d0-4516-a147-72161d566865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-id_gender-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-id_gender-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfa4f343-93cf-42e5-9632-2e993b7cbd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_gender</value>
      <webElementGuid>4c8f577f-95c5-4a29-b9d9-431f9f087553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-id_gender-2</value>
      <webElementGuid>ae5a3d22-290e-478e-891e-2c823c9323bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1049e938-cea9-4f7d-9404-c3c84eb0f220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>647c604f-3d6e-4d8d-90c5-045da335d907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-id_gender-2&quot;)</value>
      <webElementGuid>c05fc285-2044-4c84-8535-45b4242d7462</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-id_gender-2']</value>
      <webElementGuid>b677ec9b-8069-41c6-ab91-e6fad4ae5c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer-form']/div/div/div/label[2]/span/input</value>
      <webElementGuid>a957a387-9c40-484b-b12f-4a0361211a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/input</value>
      <webElementGuid>5f8cb9b9-6c34-4b67-b00d-a5daedbdafd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'id_gender' and @id = 'field-id_gender-2' and @type = 'radio']</value>
      <webElementGuid>f12e407e-b5fc-4167-a9a6-abf7955c219b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
